# LTA DataMall API 配置
API_KEY = "zv7bb9ZNTVKLgh4cMALjMQ=="
API_BASE_URL = "https://datamall2.mytransport.sg/ltaodataservice"

# 输出目录配置
OUTPUT_DIR = "Dynamic_2026_03_16"
STATIC_DATA_DIR = "Static_ 2026_03"

# 实时监控配置
MONITORING_DEFAULT_DURATION_HOURS = 240
MONITORING_DEFAULT_INTERVAL_MINUTES = 5

# API请求限制（避免被封号）
REQUEST_TIMEOUT_SECONDS = 30
MAX_RETRIES = 3
MIN_REQUEST_INTERVAL_SECONDS = 1
PAGINATION_BATCH_SIZE = 500
