#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Step 7.3.2B — Route Structure / Path Choice Diagnosis

Use the existing MATSim plans.xml.gz + trips.csv.gz and the frozen
network_links_source_copy.csv to diagnose actual route structure.

This is diagnostic only:
  - no OD change
  - no network change
  - no capacity change
  - no lambda change
  - no population regeneration

Main outputs:
  reports/od_route_diagnosis_7_3_2b/
      route_agent_summary.csv
      route_class_summary.csv
      route_transition_matrix.csv
      route_od_consistency.csv
      route_diagnosis_summary.json
      STEP7_3_2B_REPORT.md (generated by the script)

Questions answered:
  1. What fraction of sampled vehicle routes use motorway?
  2. How much route length is motorway / motorway_link / primary / etc.?
  3. How often do routes contain motorway -> motorway_link -> motorway?
  4. How many OD pairs have multiple distinct routes in this it.0?
  5. Are the same motorway corridors repeatedly used?
"""

from __future__ import annotations

import argparse
import collections
import gzip
import hashlib
import json
import re
from pathlib import Path
import xml.etree.ElementTree as ET

import numpy as np
import pandas as pd


ROOT_DEFAULT = Path(r"D:\Luan\2026-05\2_Singapore")
NETWORK_DEFAULT = Path(
    "reports/matsim_network/network_links_source_copy.csv"
)
TRIPS_DEFAULT = Path(
    "reports/matsim_assignment_6_3_3b/"
    "lambda_0p050/ITERS/it.0/"
    "output_trips.csv.gz"
)
PLANS_DEFAULT = Path(
    "reports/matsim_assignment_6_3_3b/"
    "lambda_0p050/ITERS/it.0/"
    "output_plans.xml.gz"
)

OUT = Path("reports/od_route_diagnosis_7_3_2b")


def find_existing(root: Path, explicit: Path, patterns):
    if explicit and (root / explicit).exists():
        return root / explicit

    files = []
    for pattern in patterns:
        files.extend(root.rglob(pattern))

    if not files:
        raise FileNotFoundError(
            f"无法找到输入文件: {patterns}"
        )

    # Prefer lambda 0.050 and it.0 when several exist.
    files = sorted(
        files,
        key=lambda p: (
            "lambda_0p050" not in str(p),
            "it.0" not in str(p).lower(),
            len(str(p)),
            str(p),
        ),
    )
    return files[0]


def load_network(root: Path, explicit: Path):
    path = find_existing(
        root,
        explicit,
        [
            "network_links_source_copy.csv",
        ],
    )

    e = pd.read_csv(
        path,
        encoding="utf-8-sig",
        low_memory=False,
    )

    # Link ids in plans/routes are "e{from_node}_{to_node}"
    # (the Step 6.1 convention). The source-copy CSV has no
    # explicit id column, so build it.
    if "matsim_link_id" not in e.columns:
        if {"from_node", "to_node"} - set(e.columns):
            raise ValueError(
                "network 缺 from_node/to_node，无法构造 matsim_link_id"
            )
        e["matsim_link_id"] = (
            "e"
            + e["from_node"].astype(str)
            + "_"
            + e["to_node"].astype(str)
        )

    required = {
        "highway",
        "length_m",
    }
    missing = required - set(e.columns)
    if missing:
        raise ValueError(
            f"network 缺字段: {sorted(missing)}"
        )

    e["matsim_link_id"] = e[
        "matsim_link_id"
    ].astype(str)

    e["highway"] = (
        e["highway"]
        .astype(str)
        .str.lower()
        .str.strip()
    )

    e["length_m"] = pd.to_numeric(
        e["length_m"],
        errors="coerce",
    ).fillna(0.0)

    # Duplicate ids would make route classification ambiguous.
    if e["matsim_link_id"].duplicated().any():
        dup = int(
            e["matsim_link_id"].duplicated().sum()
        )
        raise ValueError(
            f"network 出现 {dup} 个重复 matsim_link_id"
        )

    e = e.set_index(
        "matsim_link_id"
    )

    # Dict views for fast per-link lookups in route loops
    # (200k routes x tens of links; df.loc per link is far too slow).
    hw = e["highway"].to_dict()
    ln = e["length_m"].to_dict()

    return e, hw, ln, path


def load_trips(root: Path, explicit: Path):
    path = find_existing(
        root,
        explicit,
        [
            "output_trips.csv.gz",
            "*trips*.csv.gz",
            "*trips*.xml.gz",
            "*trips*.csv",
        ],
    )

    # Current Step 6.3.3B output is CSV-like semicolon separated.
    trips = pd.read_csv(
        path,
        sep=";",
        compression="infer",
        low_memory=False,
    )

    required = {
        "person",
        "start_link",
        "end_link",
        "main_mode",
    }
    missing = required - set(trips.columns)
    if missing:
        raise ValueError(
            f"trips 缺字段: {sorted(missing)}"
        )

    trips["person"] = trips[
        "person"
    ].astype(str)

    trips["start_link"] = trips[
        "start_link"
    ].astype(str)

    trips["end_link"] = trips[
        "end_link"
    ].astype(str)

    return trips, path


def parse_plans_routes(root: Path, explicit: Path):
    path = find_existing(
        root,
        explicit,
        [
            "output_plans.xml.gz",
            "*plans*.xml.gz",
            "*plans*.xml",
        ],
    )

    route_hashes = []
    route_links = []
    persons = []

    current_person = None

    route_re = re.compile(
        r'<route[^>]*type="links"[^>]*>(.*?)</route>'
    )
    person_re = re.compile(
        r'<person[^>]*id="([^"]+)"'
    )

    with gzip.open(
        path,
        "rt",
        encoding="utf-8",
        errors="replace",
    ) as f:
        for line in f:
            pm = person_re.search(line)
            if pm:
                current_person = pm.group(1)

            if (
                '<route ' in line
                and 'type="links"' in line
            ):
                rm = route_re.search(line)
                if not rm:
                    continue

                links = rm.group(1).strip().split()
                h = hashlib.md5(
                    " ".join(links).encode(
                        "utf-8"
                    )
                ).hexdigest()

                persons.append(
                    current_person
                )
                route_hashes.append(h)
                route_links.append(links)

    if not persons:
        raise ValueError(
            f"plans 中没有找到 type=links route: {path}"
        )

    routes = pd.DataFrame(
        {
            "person": persons,
            "route_hash": route_hashes,
            "route_links": route_links,
        }
    )

    return routes, path


def classify_route(
    links,
    hw,
    ln,
):
    classes = []
    lengths = []

    missing = 0

    for link in links:
        h = hw.get(link)
        if h is None:
            missing += 1
            classes.append("UNKNOWN")
            lengths.append(0.0)
            continue

        classes.append(h)
        lengths.append(
            float(ln.get(link, 0.0))
        )

    length_total = float(
        np.sum(lengths)
    )

    motorway_len = float(
        sum(
            length
            for cls, length in zip(
                classes,
                lengths,
            )
            if cls == "motorway"
        )
    )

    ramp_len = float(
        sum(
            length
            for cls, length in zip(
                classes,
                lengths,
            )
            if cls == "motorway_link"
        )
    )

    motorway_or_ramp = float(
        motorway_len + ramp_len
    )

    # Transition patterns.
    transitions = collections.Counter(
        zip(
            classes[:-1],
            classes[1:],
        )
    )

    has_mw = "motorway" in classes
    has_ramp = (
        "motorway_link" in classes
    )

    has_mw_ramp_mw = any(
        a == "motorway"
        and b == "motorway_link"
        and c == "motorway"
        for a, b, c in zip(
            classes[:-2],
            classes[1:-1],
            classes[2:],
        )
    )

    return {
        "length_total_m": length_total,
        "motorway_length_m": motorway_len,
        "motorway_link_length_m": ramp_len,
        "motorway_or_ramp_length_m": motorway_or_ramp,
        "motorway_length_share": (
            motorway_len / length_total
            if length_total > 0
            else 0.0
        ),
        "motorway_link_length_share": (
            ramp_len / length_total
            if length_total > 0
            else 0.0
        ),
        "motorway_or_ramp_length_share": (
            motorway_or_ramp / length_total
            if length_total > 0
            else 0.0
        ),
        "has_motorway": has_mw,
        "has_motorway_link": has_ramp,
        "has_motorway_ramp_motorway": (
            has_mw_ramp_mw
        ),
        "route_link_count": len(links),
        "unknown_link_count": missing,
        "classes": classes,
        "lengths": lengths,
        "transitions": transitions,
    }


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--project-root",
        type=Path,
        default=ROOT_DEFAULT,
    )

    parser.add_argument(
        "--network",
        type=Path,
        default=NETWORK_DEFAULT,
    )

    parser.add_argument(
        "--trips",
        type=Path,
        default=TRIPS_DEFAULT,
    )

    parser.add_argument(
        "--plans",
        type=Path,
        default=PLANS_DEFAULT,
    )

    args = parser.parse_args()

    root = args.project_root
    out = root / OUT
    out.mkdir(
        parents=True,
        exist_ok=True,
    )

    print("=" * 72)
    print(
        "Step 7.3.2B | Route Structure Diagnosis"
    )
    print("=" * 72)

    network, hw, ln, network_path = load_network(
        root,
        args.network,
    )

    trips, trips_path = load_trips(
        root,
        args.trips,
    )

    routes, plans_path = parse_plans_routes(
        root,
        args.plans,
    )

    # One route should exist for each car trip.
    route_n = len(routes)
    trip_n = len(trips)

    if route_n != trip_n:
        print(
            f"WARN: trips={trip_n:,}, routes={route_n:,}"
        )

    merged = trips[
        [
            "person",
            "start_link",
            "end_link",
        ]
    ].merge(
        routes,
        on="person",
        how="inner",
    )

    if merged.empty:
        raise ValueError(
            "trips 与 plans 的 person 无法连接"
        )

    diagnostics = []

    # Overall route-class usage accumulators (single pass).
    class_length = collections.defaultdict(float)
    class_route_count = collections.defaultdict(int)
    transition_counter = collections.Counter()
    route_pattern_counts = collections.Counter()

    for r in merged.itertuples(
        index=False
    ):
        d = classify_route(
            r.route_links,
            hw,
            ln,
        )

        diagnostics.append(
            {
                "person": r.person,
                "start_link": r.start_link,
                "end_link": r.end_link,
                "route_hash": r.route_hash,
                **{
                    k: v
                    for k, v in d.items()
                    if k not in {
                        "classes",
                        "transitions",
                    }
                },
            }
        )

        classes = d["classes"]

        for cls, length in zip(
            classes,
            d["lengths"],
        ):
            class_length[
                cls
            ] += length

        for cls in set(classes):
            class_route_count[
                cls
            ] += 1

        transition_counter.update(
            d["transitions"]
        )

        if d[
            "has_motorway_ramp_motorway"
        ]:
            route_pattern_counts[
                "motorway→motorway_link→motorway"
            ] += 1

    route_df = pd.DataFrame(
        diagnostics
    )

    route_df.to_csv(
        out / "route_agent_summary.csv",
        index=False,
        encoding="utf-8-sig",
    )

    class_rows = []
    total_length = sum(
        class_length.values()
    )

    for cls, length in sorted(
        class_length.items(),
        key=lambda kv: -kv[1],
    ):
        class_rows.append(
            {
                "highway": cls,
                "total_route_length_km":
                    length / 1000.0,
                "route_length_share":
                    length / total_length
                    if total_length > 0
                    else 0.0,
                "route_count_using_class":
                    class_route_count[cls],
                "route_use_rate":
                    class_route_count[cls]
                    / len(merged)
                    if len(merged) > 0
                    else 0.0,
            }
        )

    pd.DataFrame(
        class_rows
    ).to_csv(
        out / "route_class_summary.csv",
        index=False,
        encoding="utf-8-sig",
    )

    trans_rows = [
        {
            "from_highway": a,
            "to_highway": b,
            "count": n,
        }
        for (a, b), n in transition_counter.most_common()
    ]

    pd.DataFrame(
        trans_rows
    ).to_csv(
        out / "route_transition_matrix.csv",
        index=False,
        encoding="utf-8-sig",
    )

    # OD route consistency.
    merged["route_hash"] = (
        merged["route_hash"]
        .astype(str)
    )

    od_consistency = (
        merged.groupby(
            [
                "start_link",
                "end_link",
            ],
            as_index=False,
        )
        .agg(
            agents=(
                "person",
                "count",
            ),
            unique_routes=(
                "route_hash",
                "nunique",
            ),
        )
    )

    od_consistency[
        "multiple_route"
    ] = (
        od_consistency[
            "unique_routes"
        ] > 1
    )

    od_consistency.to_csv(
        out / "route_od_consistency.csv",
        index=False,
        encoding="utf-8-sig",
    )

    # Agent-level route diagnosis.
    summary = {
        "step": "7.3.2B",
        "status": "PASS",
        "network_file": str(
            network_path
        ),
        "trips_file": str(
            trips_path
        ),
        "plans_file": str(
            plans_path
        ),
        "trip_count": int(
            trip_n
        ),
        "route_count": int(
            route_n
        ),
        "joined_count": int(
            len(merged)
        ),
        "routes_using_motorway": int(
            route_df.has_motorway.sum()
        ),
        "routes_using_motorway_rate": float(
            route_df.has_motorway.mean()
        ),
        "routes_using_motorway_link": int(
            route_df.has_motorway_link.sum()
        ),
        "routes_using_motorway_link_rate": float(
            route_df.has_motorway_link.mean()
        ),
        "routes_with_motorway_ramp_motorway": int(
            route_df.has_motorway_ramp_motorway.sum()
        ),
        "routes_with_motorway_ramp_motorway_rate": float(
            route_df.has_motorway_ramp_motorway.mean()
        ),
        "median_motorway_length_share": float(
            route_df.motorway_length_share.median()
        ),
        "median_motorway_ramp_length_share": float(
            route_df.motorway_or_ramp_length_share.median()
        ),
        "unknown_route_link_count": int(
            route_df.unknown_link_count.sum()
        ),
        "od_pairs": int(
            len(od_consistency)
        ),
        "od_pairs_with_multiple_routes": int(
            od_consistency.multiple_route.sum()
        ),
        "od_multiple_route_rate": float(
            od_consistency.multiple_route.mean()
        ),
        "most_common_route_pattern": (
            route_pattern_counts.most_common(10)
        ),
        "frozen_parameters_unchanged": True,
        "lambda_frozen": False,
    }

    with open(
        out / "route_diagnosis_summary.json",
        "w",
        encoding="utf-8",
    ) as f:
        json.dump(
            summary,
            f,
            ensure_ascii=False,
            indent=2,
        )

    report = f"""# Step 7.3.2B — Route Structure / Path-choice Diagnosis

## Status

**PASS（诊断层，不修改模型）**

- Network: `{network_path}`
- Trips: `{trips_path}`
- Plans: `{plans_path}`
- Joined trips/routes: **{len(merged):,}**

## Core results

- Routes using motorway: **{summary["routes_using_motorway_rate"]:.2%}**
- Routes using motorway_link: **{summary["routes_using_motorway_link_rate"]:.2%}**
- Routes containing motorway→motorway_link→motorway:
  **{summary["routes_with_motorway_ramp_motorway_rate"]:.2%}**
- Median motorway length share:
  **{summary["median_motorway_length_share"]:.2%}**
- Median motorway-or-ramp length share:
  **{summary["median_motorway_ramp_length_share"]:.2%}**
- OD pairs with multiple distinct routes:
  **{summary["od_multiple_route_rate"]:.4%}**

## Interpretation

This step diagnoses actual it.0 route structure. It does not change OD,
network, capacity, population, departure profile or lambda.

Use the outputs to distinguish:

1. motorway under-use;
2. motorway usage with route fragmentation;
3. deterministic single-route assignment within OD pairs.

Further comparison with LTA CATA/SLIP_ROAD requires combining this
route classification with the frozen Step 7.1 calibration target.
"""

    (out / "STEP7_3_2B_REPORT.md").write_text(
        report,
        encoding="utf-8",
    )

    print("-" * 72)
    print(
        f"Joined trips/routes: {len(merged):,}"
    )
    print(
        "Motorway route use: "
        f"{summary['routes_using_motorway_rate']:.2%}"
    )
    print(
        "Motorway-link route use: "
        f"{summary['routes_using_motorway_link_rate']:.2%}"
    )
    print(
        "Motorway→ramp→motorway: "
        f"{summary['routes_with_motorway_ramp_motorway_rate']:.2%}"
    )
    print(
        "ODs with >1 route: "
        f"{summary['od_multiple_route_rate']:.2%}"
    )
    print(
        f"Output: {out}"
    )
    print("=" * 72)


if __name__ == "__main__":
    main()
